# Numpy
A Python library used for working with arrays. In Python, we use the list for the array processor intensive. A NumPy array is a powerful N-dimensional array object. It provides an array object much faster than inbuilt Python lists.

The [Numpy Documentation](https://numpy.org/doc/2.2/user/absolute_beginners.html#) is very user friendly.

In [2]:
# importing Numpy library
import numpy as np

| Feature | List | NPArray |
| ------ | -----: | -----: |
| Builtin | Y | N |
| Multiple data types | Y | N |
| Multiple dimensions | N | Y |
| Arithmetic Operations | N | Y |
| Process intensive | Y | N |
| Optimised for ML | N | Y |

In [3]:
# create a list
list_1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# creating numpy array
sample_array_1 = np.array(list_1)

print(f"List in python :\n{list_1}\n")

print(f"Numpy Array in python :\n{sample_array_1}")

List in python :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Numpy Array in python :
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# create a second list
list_2 = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
sample_array_2 = np.array(list_2)
# creating numpy array
sample_array_3 = np.array([list_1, list_2])

sample_array_4 = np.column_stack((sample_array_1,sample_array_2))

print(f"List in python :\n{list_1}\n")

print(f"List_2 in python :\n{list_2}\n")

print(f"2:10 Numpy Multi-dimensional Array in Python :\n{sample_array_3}\n")
print(f"10:2 Numpy Multi-dimensional Array in Python :\n{sample_array_4}\n")

List in python :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

List_2 in python :
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

2:10 Numpy Multi-dimensional Array in Python :
[[0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]]

10:2 Numpy Multi-dimensional Array in Python :
[[0 9]
 [1 8]
 [2 7]
 [3 6]
 [4 5]
 [5 4]
 [6 3]
 [7 2]
 [8 1]
 [9 0]]



#### Array attributes

ndim, shape, size, and dtype are attributes of an Numpy array.

In [5]:
# An integer that tells us how many dimensions the array have.
print(f"Number of dimensions 1: {sample_array_1.ndim}")
print(f"Number of dimensions 2: {sample_array_2.ndim}")
print(f"Number of dimensions 3: {sample_array_3.ndim}")
print(f"Number of dimensions 4: {sample_array_4.ndim}")

Number of dimensions 1: 1
Number of dimensions 2: 1
Number of dimensions 3: 2
Number of dimensions 4: 2


In [8]:
# A tuple of non-negative integers that specify the number of
# elements along each dimension called the shape.
print(f"Shape of array 1: {sample_array_1.shape}")
print(f"Shape of array 2: {sample_array_2.shape}")
print(f"Shape of array 3: {sample_array_3.shape}")
print(f"Shape of array 4: {sample_array_4.shape}")

Shape of array 1: (10,)
Shape of array 2: (10,)
Shape of array 3: (2, 10)
Shape of array 4: (10, 2)


In [7]:
# An object describing the type of the elements in the array.
print(f"Data type of array 1: {sample_array_1.dtype}")
print(f"Data type of array 2: {sample_array_2.dtype}")
print(f"Data type of array 3: {sample_array_3.dtype}")
print(f"Data type of array 4: {sample_array_4.dtype}")

Data type of array 1: int64
Data type of array 2: int64
Data type of array 3: int64
Data type of array 4: int64


In [6]:
# The fixed, total number of elements in array
print(f"Size of array 1: {sample_array_1.size}")
print(f"Size of array 2: {sample_array_2.size}")
print(f"Size of array 3: {sample_array_3.size}")
print(f"Size of array 4: {sample_array_4.size}")    

Size of array 1: 10
Size of array 2: 10
Size of array 3: 20
Size of array 4: 20


#### Reshapping an Array

Reshaping will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with a size of 10, your new array also has a total of 10 elements.

In [ ]:
#Rehape the array
print(f"Array 1:\n{sample_array_1}\n")
reshape = sample_array_1.reshape(2,5) # 2*5 = size of array
print(f"Reshaped array:\n{reshape}")

In [ ]:
# Reshape the array to 2D array from a 1D array with 1 row and 10 columns
print(f"Array 1:\n{sample_array_1}\n")
reshape = sample_array_1.reshape(1,10)
print(f"Reshaped array:\n{reshape}")

In [ ]:
# Reshape the array to a 1D array from a 2D array with 10 rows and 1 column
print(f"Reshaped array:\n{reshape}\n")
flatten = reshape.flatten()
print(f"Flattened array:\n{flatten}")